env:
  global:
    - CC_TEST_REPORTER_ID=5d07064da85cd869eab5334ebeb5c130c121be9c684d83c6e928a8bfdda8b9fb
rvm:
  - 1.8.7
  - 1.9.3
  - ree
  - 2.0.0

gemfile:
  - Gemfile

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: "bundle exec rspec spec"

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
